#!/bin/bash

export PATH=$PATH:twisted-12.2.0/bin
export PYTHONPATH=$PYTHONPATH:twisted-12.2.0/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:twisted-12.2.0/lib

export PYTHONPATH=$PYTHONPATH:twitty-twister

$@
